config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'quiz/try'
  post 'quiz/user_answer'

  root 'users#index'

  resources :users, only: %i[create new edit update]
  resource :session, only: %i[new create destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "rails-ujs" %>
  </head>

  <body>
    <% unless yield(:page_title) == "Quiz" %>
      <header class="p-3 bg-dark text-white">
        <div class="container">
          <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <% unless user_signed_in? %>
                <li><%= link_to 'Регистрация', new_user_path, class: 'nav-link px-2 text-white' %></li>
                <li><%= link_to 'Войти', new_session_path, class: 'nav-link px-2 text-white' %></li>
              <% else %>
                <li><%= link_to 'Профиль', root_path, class: 'nav-link px-2 text-white', data: { method: :delete }  %></li>
                <li><%= link_to 'Тестирование', quiz_try_path, class: 'nav-link px-2 text-white', data: {turbo: false} %></li>
                <li><%= link_to 'Выйти', session_path, class: 'nav-link px-2 text-white', data: { method: :delete } %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </header>
    <% end %>

    <main class="container">
      <% flash.each do |k, v| %>
        <%= tag.div v, class: "alert alert-#{k} mt-4", role: 'alert' %>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>